version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - moshe
  ignore:
  - dependency-name: aws-sdk
    versions:
    - "> 2.488.0"
  - dependency-name: redis
    versions:
    - 3.0.2
    - 3.1.0
    - 3.1.1
  - dependency-name: eslint-plugin-react
    versions:
    - 7.22.0
    - 7.23.1
  - dependency-name: commander
    versions:
    - 7.0.0
    - 7.1.0
  - dependency-name: lodash
    versions:
    - 4.17.20
