language: node_js
sudo: false
node_js:
  - "node"
  - "lts/*"
install:
  - npm install
  - pip install --user git+https://github.com/moshe/pytest-tomato.git@debug#subdirectory=tomato-lib
script:
  - npm test
after_script:
  - tomato eslint.xml
